class MockData {
  static List<Map<String, dynamic>> tasksData = [
    {
      'id': 1,
      'name': 'Алгебра',
      'teacherId': 1,
      'description': 'Решить пример №202',
      'fileLink': '',
      'startDate': DateTime(2024, 4, 1),
      'endDate': DateTime(2024, 5, 7),
    },
    {
      'id': 2,
      'name': 'Биология',
      'teacherId': 3,
      'description': 'Сфотографировать капибару',
      'fileLink': 'capibara_4k.png',
      'startDate': DateTime(2024, 4, 3),
      'endDate': DateTime(2024, 5, 5),
    },
    {
      'id': 3,
      'name': 'Литература',
      'teacherId': 3,
      'description': 'Выложить 3 том мертвых душ',
      'fileLink': 'gogol_rule34_collection.pdf',
      'startDate': DateTime(2024, 4, 5),
      'endDate': DateTime(2024, 5, 12),
    },
  ];

  static List<Map<String, dynamic>> taskAnswersData = [
    {
      'id': 1,
      'taskId': 1,
      'studentId': 4,
      'teacherComment': "Коши Коши Коши",
      'grade': 2,
      'answerLink': "http://example.com/answer1.pdf",
    },
    {
      'id': 2,
      'taskId': 2,
      'studentId': 4,
      'teacherComment': "Милый!",
      'grade': 5,
      'answerLink': "http://example.com/answer2.docx",
    },
    {
      'id': 3,
      'taskId': 3,
      'studentId': 4,
      'teacherComment': null,
      'grade': null,
      'answerLink': null,
    },
  ];


  static List<Map<String, dynamic>> usersData = [
    {
      'id': 1,
      'login': '2',
      'password': '2',
      'name': 'Иван',
      'surname': 'Иванов',
      'patronymic': 'Иванович',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar1.jpg',
      'projectId': '',
      'groupId': '',
      'role': 'professor',
    },
    {
      'id': 2,
      'login': '3',
      'password': '3',
      'name': 'Петр',
      'surname': 'Петров',
      'patronymic': 'Петрович',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar2.jpg',
      'projectId': '',
      'groupId': '',
      'role': 'admin',
    },
    {
      'id': 3,
      'login': 'anton',
      'password': '1233',
      'name': 'Антон',
      'surname': 'Антонов',
      'patronymic': 'Антонович',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar2.jpg',
      'projectId': '',
      'groupId': '',
      'role': 'professor',
    },
    {
      'id': 4,
      'login': '1',
      'password': '1',
      'name': 'Данила',
      'surname': 'Третьяков',
      'patronymic': 'Сергеевич',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar1.jpg',
      'projectId': '',
      'groupId': '6',
      'role': 'student',
    },
    {
      'id': 5,
      'login': '12',
      'password': '12',
      'name': 'Дан',
      'surname': 'Тре',
      'patronymic': 'Сер',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar1.jpg',
      'projectId': '',
      'groupId': '2',
      'role': 'student',
    },
    {
      'id': 6,
      'login': '123',
      'password': '123',
      'name': 'Да',
      'surname': 'Тр',
      'patronymic': 'Се',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar1.jpg',
      'projectId': '',
      'groupId': '1',
      'role': 'student',
    },
    {
      'id': 7,
      'login': '1234',
      'password': '1234',
      'name': 'Д',
      'surname': 'Т',
      'patronymic': 'С',
      'email': 'email',
      'avatarLink': 'http://example.com/avatar1.jpg',
      'projectId': '',
      'groupId': '2',
      'role': 'student',
    },
  ];
}
