version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=projectPalDB'
      - 'POSTGRES_PASSWORD=W8r}a*B#~4'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projectPalDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: W8r}a*B#~4
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres-data:
    driver: local

networks:
  backend:
    driver: bridge
